- hosts: dev 
  
  vars_files:
    - vars/python_packages.yml
    - vars/packages.yml

  tasks:

  - name: apt-get update
    apt: update_cache=yes

  - name: Install package list general
    apt: name={{item}} state=installed
    with_items: packages_to_install

  - name: download vagrant deb
    get_url: 
      url: https://releases.hashicorp.com/vagrant/1.9.2/vagrant_1.9.2_x86_64.deb 
      dest: /tmp/vagrant_1.9.2_x86_64.deb
      mode: 0400

  - name: install vagrant
    apt: deb=/tmp/vagrant_1.9.2_x86_64.deb state=installed

  - name: download terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
      dest: /tmp/terraform_0.8.8_linux_amd64.zip
      mode: 0400

  - unarchive:
      src: /tmp/terraform_0.8.8_linux_amd64.zip
      dest: /usr/local/bin

  - name: "install python packages: {{ python_packages_to_install }}"
    pip: name="{{ python_packages_to_install | join(' ') }}"
    with_items: python_packages_to_install
